[install]
minimumReleaseAge = 604800 # 7 days
minimumReleaseAgeExcludes = ["@types/bun", "typescript"]

[run]
bun = true # equivalent to `bun --bun` for all `bun run` commands

[test]
randomize = true
