# ~/.config/helix/config.toml

theme = "focus_nova"

[editor]
completion-timeout = 5
completion-trigger-len = 3
middle-click-paste = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.gutters.line-numbers]
min-width = 1

[editor.indent-guides]
render = true
character = "â•Ž"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "warning"
prefix-len = 2

[editor.lsp]
snippets = false

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator"]
center = ["file-name"]
right = ["diagnostics", "selections", "register", "position", "file-encoding"]

[editor.whitespace]
render = "all"
